version: '3.9'

services:
  
  elasticsearch:
    image: elasticsearch:8.2.3
    restart: always
    volumes:
      - elastic_data:/usr/share/elasticsearch/data/
    environment:
      ES_JAVA_OPTS: "-Xms256m -Xmx256m"
      discovery.type: multi-node
      xpack.security.enabled: "false"
      vm.max_map_count: "262144"
      cluster.initial_master_nodes: "10.0.7.170"
    ports:
        - '9200:9200'
        - '9300:9300'
    networks:
        - elk
  
  logstash:
    image: logstash:8.2.3
    restart: always
    volumes:
      - logstash:/logstash_dir
    command: logstash -f /logstash_dir/logstash.conf
    depends_on: 
      - elasticsearch
    ports:
      - '9600:9600'
    environment:
      LS_JAVA_OPTS: "-Xms256m -Xmx256m"
    networks:
      - elk

  kibana:
    image: kibana:8.2.3
    restart: always
    ports:
      - '5601:5601'
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - elk

volumes:
  elastic_data: {}
  logstash: {}

networks:
  elk:
    name: elk
    external: true