version: '3.9'

services:
  
  elasticsearch:
    image: elasticsearch:8.2.3
    volumes:
      - elastic_data:/usr/share/elasticsearch/data/
    environment:
      ES_JAVA_OPTS: "-Xms2g -Xmx2g"
      discovery.type: single-node
    ports:
        - '9200:9200'
        - '9300:9300'
    networks:
        - elk
  
  logstash:
    image: logstash:8.2.3
    volumes:
      - logstash-pipeline:/usr/share/logstash/pipeline
    depends_on: 
      - elasticsearch
    ports:
      - '12201:12201/udp'
    environment:
      ES_JAVA_OPTS: "-Xms2g -Xmx2g"
    networks:
      - elk
    deploy:
      mode: global

  kibana:
    image: kibana:8.2.3
    ports:
      - '5601:5601'
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - elk

volumes:
  elastic_data: 
    driver: local
  logstash-pipeline: 
    driver: local

networks:
  elk:
    name: elk
    external: true