version: '3.9'

services:
  
  elasticsearch:
    image: elasticsearch
    container_name: elasticsearch
    restart: always
    volumes:
      - elastic_data:/usr/share/elasticsearch/data/
    environment:
      ES_JAVA_OPTS: "-Xms256m -Xms1024m"
      discovery.type: multi-node
    ports:
        - '9200:9200'
        - '9300:9300'
    networks:
        - elk
  
  logstash:
    image: logstash
    container_name: logstash
    restart: always
    volumes:
      - ./logstash:/logstash_dir
    command: logstash -f /logstash_dir/logstash.conf
    depends_on: elasticsearch
    ports:
      - '9600:9600'
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms1024m"
    networks:
      - elk

  kibana:
    image: kibana
    container_name: kibana
    restart: always
    ports:
      - '5601:5601'
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - elk

volumes:
  elastic_data: {}

networks:
  elk:
    name: elk
    external: true