version: '3.9'

services:
  
  elasticsearch:
    image: elasticsearch:8.2.3
    volumes:
      - elastic_data:/usr/share/elasticsearch/data/
    environment:
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-}
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      discovery.type: single-node
      reindex.ssl.verification_mode: none
      xpack.security.http.ssl.enabled: 'false'
    ports:
        - '9200:9200'
        - '9300:9300'
    networks:
        - elk
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"

  logstash:
    image: logstash:8.2.3
    volumes:
      - logstash-pipeline:/usr/share/logstash/pipeline
    depends_on: 
      - elasticsearch
    ports:
      - '12201:12201/udp'
    environment:
      ES_JAVA_OPTS: "-Xms256m -Xmx256m"
      LOGSTASH_INTERNAL_PASSWORD: ${LOGSTASH_INTERNAL_PASSWORD:-}
    networks:
      - elk
    deploy:
      mode: global
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"

  kibana:
    image: kibana:8.2.3
    ports:
      - '5601:5601'
    environment:
      ELASTICSEARCH_URL: 'http://elasticsearch:9200'
      KIBANA_SYSTEM_PASSWORD: ${KIBANA_SYSTEM_PASSWORD:-}

    depends_on:
      - elasticsearch
    networks:
      - elk
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"


volumes:
  elastic_data: 
    driver: local
  logstash-pipeline: 
    driver: local

networks:
  elk:
    name: elk
    external: true